openapi: 3.0.3
info:
  title: Chat App API
  version: 1.0.0

paths:
  /signup:
    post:
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '401':
          description: 登录失败
          content:
            text/plain:
              schema:
                type: string
        default:
          description: 通用错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"


  /login:
    post:
      summary: 用户登录
      operationId: LoginPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        '401':
          description: 登录失败
          content:
            text/plain:
              schema:
                type: string
        default:
          description: 通用错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    SignupResponse:
      type: object
      properties:
        message:
          type: string
      

    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      required:
        - message
        - token
      properties:
        message:
          type: string
        token:
          type: string
      

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
