openapi: 3.0.3
info:
  title: Chat App API
  version: 1.0.0

paths:
  /signup:
    post:
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '200':
          description: 注册成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    SignupResponse:
      type: object
      properties:
        message:
          type: string
